# Generated by Django 5.0.7 on 2025-01-16 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        help_text="Unique identifier, max 30 characters.",
                        max_length=30,
                        unique=True,
                        verbose_name="Account ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Client's full name, max 100 characters.",
                        max_length=100,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        help_text="Specify the person's gender.",
                        max_length=6,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Optional. Select a birth date from the date picker.",
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. Max size: 5MB. Allowed formats: JPG/JPEG/PNG. Best size: 800x800px.",
                        null=True,
                        upload_to="client_photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                            django.core.validators.MaxLengthValidator(5242880),
                        ],
                        verbose_name="Photo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional. Write the client's email address.",
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "mobile_no",
                    models.CharField(
                        help_text="Enter a 10-digit Indian mobile number.",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^\\d{10}$",
                            )
                        ],
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Unique account username, between 3 and 50 characters.",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Username must be at least 3 characters long."
                            )
                        ],
                        verbose_name="Username",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Set a password, between 5 and 30 characters.",
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, "Password must be at least 5 characters long."
                            )
                        ],
                        verbose_name="Password",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Inactive",
                        help_text="Activate or deactivate the account.",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notify_via_email_sms",
                    models.BooleanField(
                        default=True,
                        help_text="Check to send a notification to the client via email/SMS.",
                        verbose_name="Email/SMS Notification",
                    ),
                ),
            ],
        ),
    ]
