# Generated by Django 5.0.7 on 2025-01-16 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=30, unique=True)),
                ("machine_name", models.CharField(max_length=150)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="machine_photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Available", "Available"), ("Sold", "Sold")],
                        default="Available",
                        max_length=10,
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
            },
        ),
    ]
