# Generated by Django 5.0.7 on 2025-01-28 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_authorize_company_country_localization_machine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.location",
            ),
        ),
    ]
