# Generated by Django 5.0.7 on 2025-01-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_machine_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="location",
            field=models.TextField(null=True, unique=True),
        ),
    ]
