# Generated by Django 5.0.7 on 2025-01-16 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="machine_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
