# Generated by Django 5.0.7 on 2025-01-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_machine_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=150, unique=True)),
                ("brand_name", models.CharField(blank=True, max_length=150, null=True)),
                ("company_phone", models.CharField(max_length=30)),
                ("website", models.URLField(blank=True, max_length=150, null=True)),
                ("company_email", models.EmailField(max_length=254)),
                ("company_mobile_no", models.CharField(max_length=10)),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=10, null=True)),
                ("comm_address", models.CharField(max_length=250)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=6, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reg_address",
                    models.CharField(blank=True, max_length=750, null=True),
                ),
                (
                    "contact_person_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_person_mobile",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "brand_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/logos/"
                    ),
                ),
                (
                    "brand_icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/icons/"
                    ),
                ),
                ("enrollment_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
