# Generated by Django 5.0.7 on 2025-01-28 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_company_associated_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="handled_by",
        ),
    ]
