# Generated by Django 5.0.7 on 2025-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_ticket_handled_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="observation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="resolution_status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="root_cause",
            field=models.TextField(blank=True, null=True),
        ),
    ]
