# Generated by Django 5.0.7 on 2025-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_localization_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
