# Generated by Django 5.0.7 on 2025-01-21 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="account_id",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Unique identifier, max 30 characters.",
                max_length=30,
                unique=True,
                verbose_name="Account ID",
            ),
        ),
    ]
