# Generated by Django 5.0.7 on 2025-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_client_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="attributes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
