# Generated by Django 5.0.7 on 2025-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_machine_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SideBarIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("icon", models.ImageField(upload_to="icon/")),
                ("date", models.DateTimeField(auto_now=True)),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="TopBarIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("icon", models.ImageField(upload_to="icon/")),
                ("date", models.DateTimeField(auto_now=True)),
                ("link", models.URLField()),
            ],
        ),
    ]
