# Generated by Django 5.0.7 on 2025-01-21 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_sidebaricon_topbaricon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_id",
            field=models.CharField(
                default=uuid.uuid1, editable=False, max_length=30, unique=True
            ),
        ),
    ]
