# Generated by Django 5.0.7 on 2025-01-22 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_ticket_ticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="account_id",
            field=models.CharField(
                auto_created=True, default=uuid.uuid4, max_length=30, unique=True
            ),
        ),
    ]
