# Generated by Django 5.0.7 on 2025-01-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_location_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.ticketpriority",
            ),
        ),
    ]
