# Generated by Django 5.0.7 on 2025-01-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_ticket_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDocs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("file", models.FileField(upload_to="docs/")),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "associated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketDocs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("file", models.FileField(upload_to="docs/")),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "associated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ticket"
                    ),
                ),
            ],
        ),
    ]
