# Generated by Django 5.0.7 on 2025-01-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_orderdocs_ticketdocs"),
    ]

    operations = [
        migrations.CreateModel(
            name="machine_attributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "associated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.machine"
                    ),
                ),
            ],
        ),
    ]
