# Generated by Django 5.0.7 on 2025-01-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_machine_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField(unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("request", models.TextField()),
            ],
        ),
    ]
