# Generated by Django 5.0.7 on 2025-01-25 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_orderstatus_ticketstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.orderstatus",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.ticketstatus",
            ),
        ),
    ]
