# Generated by Django 5.0.7 on 2025-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_order_status_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dc_copy",
            field=models.FileField(blank=True, null=True, upload_to="dc_copy"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="observation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolution_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="root_cause",
            field=models.TextField(blank=True, null=True),
        ),
    ]
