# Generated by Django 5.0.7 on 2025-01-27 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_order_dc_copy_ticket_observation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="attributes",
        ),
        migrations.RemoveField(
            model_name="order",
            name="documents",
        ),
    ]
