# Generated by Django 5.0.7 on 2025-01-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_alter_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="trash",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="trash",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="trash",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="trash",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="trash",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="trash",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="trash",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="trash",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
